/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_wolfcrypt_Fips_ErrorCallback */

#ifndef _Included_com_wolfssl_wolfcrypt_Fips_ErrorCallback
#define _Included_com_wolfssl_wolfcrypt_Fips_ErrorCallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
