/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_wolfcrypt_AesKeyWrap */

#ifndef _Included_com_wolfssl_wolfcrypt_AesKeyWrap
#define _Included_com_wolfssl_wolfcrypt_AesKeyWrap
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wolfssl_wolfcrypt_AesKeyWrap_NULL
#define com_wolfssl_wolfcrypt_AesKeyWrap_NULL 0LL
#undef com_wolfssl_wolfcrypt_AesKeyWrap_KEY_SIZE_128
#define com_wolfssl_wolfcrypt_AesKeyWrap_KEY_SIZE_128 16L
#undef com_wolfssl_wolfcrypt_AesKeyWrap_KEY_SIZE_192
#define com_wolfssl_wolfcrypt_AesKeyWrap_KEY_SIZE_192 24L
#undef com_wolfssl_wolfcrypt_AesKeyWrap_KEY_SIZE_256
#define com_wolfssl_wolfcrypt_AesKeyWrap_KEY_SIZE_256 32L
#undef com_wolfssl_wolfcrypt_AesKeyWrap_KEYWRAP_BLOCK_SIZE
#define com_wolfssl_wolfcrypt_AesKeyWrap_KEYWRAP_BLOCK_SIZE 8L
#undef com_wolfssl_wolfcrypt_AesKeyWrap_IV_SIZE
#define com_wolfssl_wolfcrypt_AesKeyWrap_IV_SIZE 8L
#undef com_wolfssl_wolfcrypt_AesKeyWrap_MIN_WRAP_INPUT_SIZE
#define com_wolfssl_wolfcrypt_AesKeyWrap_MIN_WRAP_INPUT_SIZE 16L
#undef com_wolfssl_wolfcrypt_AesKeyWrap_MIN_UNWRAP_INPUT_SIZE
#define com_wolfssl_wolfcrypt_AesKeyWrap_MIN_UNWRAP_INPUT_SIZE 24L
#undef com_wolfssl_wolfcrypt_AesKeyWrap_ENCRYPT_MODE
#define com_wolfssl_wolfcrypt_AesKeyWrap_ENCRYPT_MODE 0L
#undef com_wolfssl_wolfcrypt_AesKeyWrap_DECRYPT_MODE
#define com_wolfssl_wolfcrypt_AesKeyWrap_DECRYPT_MODE 1L
/*
 * Class:     com_wolfssl_wolfcrypt_AesKeyWrap
 * Method:    mallocNativeStruct_internal
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_wolfcrypt_AesKeyWrap_mallocNativeStruct_1internal
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_AesKeyWrap
 * Method:    wc_AesInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_AesKeyWrap_wc_1AesInit
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_AesKeyWrap
 * Method:    wc_AesFree
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_AesKeyWrap_wc_1AesFree
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_AesKeyWrap
 * Method:    wc_AesSetKey
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_AesKeyWrap_wc_1AesSetKey
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_AesKeyWrap
 * Method:    wc_AesKeyWrap_ex
 * Signature: ([BII[BI[B)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_AesKeyWrap_wc_1AesKeyWrap_1ex
  (JNIEnv *, jobject, jbyteArray, jint, jint, jbyteArray, jint, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_AesKeyWrap
 * Method:    wc_AesKeyUnWrap_ex
 * Signature: ([BII[BI[B)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_AesKeyWrap_wc_1AesKeyUnWrap_1ex
  (JNIEnv *, jobject, jbyteArray, jint, jint, jbyteArray, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
