/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_wolfcrypt_Lms */

#ifndef _Included_com_wolfssl_wolfcrypt_Lms
#define _Included_com_wolfssl_wolfcrypt_Lms
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wolfssl_wolfcrypt_Lms_NULL
#define com_wolfssl_wolfcrypt_Lms_NULL 0LL
#undef com_wolfssl_wolfcrypt_Lms_LMS_SHA256
#define com_wolfssl_wolfcrypt_Lms_LMS_SHA256 0L
#undef com_wolfssl_wolfcrypt_Lms_LMS_SHA256_192
#define com_wolfssl_wolfcrypt_Lms_LMS_SHA256_192 4096L
#undef com_wolfssl_wolfcrypt_Lms_LMS_SHAKE256
#define com_wolfssl_wolfcrypt_Lms_LMS_SHAKE256 8192L
#undef com_wolfssl_wolfcrypt_Lms_LMS_SHAKE256_192
#define com_wolfssl_wolfcrypt_Lms_LMS_SHAKE256_192 12288L
/*
 * Class:     com_wolfssl_wolfcrypt_Lms
 * Method:    mallocNativeStruct
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_wolfcrypt_Lms_mallocNativeStruct
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Lms
 * Method:    wc_LmsKey_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Lms_wc_1LmsKey_1init
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Lms
 * Method:    wc_LmsKey_free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Lms_wc_1LmsKey_1free
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Lms
 * Method:    wc_LmsKey_get_parameters
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_wolfssl_wolfcrypt_Lms_wc_1LmsKey_1get_1parameters
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Lms
 * Method:    wc_LmsKey_verify
 * Signature: ([B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_Lms_wc_1LmsKey_1verify
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_Lms
 * Method:    wc_LmsKey_import_public
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Lms_wc_1LmsKey_1import_1public
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
