/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_wolfcrypt_Sha */

#ifndef _Included_com_wolfssl_wolfcrypt_Sha
#define _Included_com_wolfssl_wolfcrypt_Sha
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wolfssl_wolfcrypt_Sha_NULL
#define com_wolfssl_wolfcrypt_Sha_NULL 0LL
#undef com_wolfssl_wolfcrypt_Sha_TYPE
#define com_wolfssl_wolfcrypt_Sha_TYPE 1L
#undef com_wolfssl_wolfcrypt_Sha_DIGEST_SIZE
#define com_wolfssl_wolfcrypt_Sha_DIGEST_SIZE 20L
/*
 * Class:     com_wolfssl_wolfcrypt_Sha
 * Method:    mallocNativeStruct
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_wolfcrypt_Sha_mallocNativeStruct
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Sha
 * Method:    initSha
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Sha_initSha
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Sha
 * Method:    shaUpdate
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Sha_shaUpdate__Ljava_nio_ByteBuffer_2J
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     com_wolfssl_wolfcrypt_Sha
 * Method:    shaUpdate
 * Signature: ([BJ)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Sha_shaUpdate___3BJ
  (JNIEnv *, jobject, jbyteArray, jlong);

/*
 * Class:     com_wolfssl_wolfcrypt_Sha
 * Method:    shaUpdate
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Sha_shaUpdate___3BII
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_Sha
 * Method:    shaFinal
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Sha_shaFinal__Ljava_nio_ByteBuffer_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Sha
 * Method:    shaFinal
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Sha_shaFinal___3B
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
