/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_wolfcrypt_Ed448 */

#ifndef _Included_com_wolfssl_wolfcrypt_Ed448
#define _Included_com_wolfssl_wolfcrypt_Ed448
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wolfssl_wolfcrypt_Ed448_NULL
#define com_wolfssl_wolfcrypt_Ed448_NULL 0LL
#undef com_wolfssl_wolfcrypt_Ed448_ED448_KEY_SIZE
#define com_wolfssl_wolfcrypt_Ed448_ED448_KEY_SIZE 57L
#undef com_wolfssl_wolfcrypt_Ed448_ED448_PUB_KEY_SIZE
#define com_wolfssl_wolfcrypt_Ed448_ED448_PUB_KEY_SIZE 57L
#undef com_wolfssl_wolfcrypt_Ed448_ED448_PRV_KEY_SIZE
#define com_wolfssl_wolfcrypt_Ed448_ED448_PRV_KEY_SIZE 114L
#undef com_wolfssl_wolfcrypt_Ed448_ED448_SIG_SIZE
#define com_wolfssl_wolfcrypt_Ed448_ED448_SIG_SIZE 114L
#undef com_wolfssl_wolfcrypt_Ed448_ED448_PREHASH_SIZE
#define com_wolfssl_wolfcrypt_Ed448_ED448_PREHASH_SIZE 64L
#undef com_wolfssl_wolfcrypt_Ed448_ED448_MAX_CONTEXT_LEN
#define com_wolfssl_wolfcrypt_Ed448_ED448_MAX_CONTEXT_LEN 255L
#undef com_wolfssl_wolfcrypt_Ed448_ED448_TYPE_PURE
#define com_wolfssl_wolfcrypt_Ed448_ED448_TYPE_PURE 0L
#undef com_wolfssl_wolfcrypt_Ed448_ED448_TYPE_PH
#define com_wolfssl_wolfcrypt_Ed448_ED448_TYPE_PH 1L
#undef com_wolfssl_wolfcrypt_Ed448_INVALID_DEVID
#define com_wolfssl_wolfcrypt_Ed448_INVALID_DEVID -2L
#undef com_wolfssl_wolfcrypt_Ed448_FN_MSG
#define com_wolfssl_wolfcrypt_Ed448_FN_MSG 0L
#undef com_wolfssl_wolfcrypt_Ed448_FN_PH_MSG
#define com_wolfssl_wolfcrypt_Ed448_FN_PH_MSG 1L
#undef com_wolfssl_wolfcrypt_Ed448_FN_PH_HASH
#define com_wolfssl_wolfcrypt_Ed448_FN_PH_HASH 2L
#undef com_wolfssl_wolfcrypt_Ed448_FN_MSG_EX
#define com_wolfssl_wolfcrypt_Ed448_FN_MSG_EX 3L
/*
 * Class:     com_wolfssl_wolfcrypt_Ed448
 * Method:    mallocNativeStruct
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_wolfcrypt_Ed448_mallocNativeStruct
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed448
 * Method:    wc_ed448_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Ed448_wc_1ed448_1init
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed448
 * Method:    wc_ed448_init_ex
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Ed448_wc_1ed448_1init_1ex
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed448
 * Method:    wc_ed448_free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Ed448_wc_1ed448_1free
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed448
 * Method:    wc_ed448_make_key
 * Signature: (Lcom/wolfssl/wolfcrypt/Rng;I)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Ed448_wc_1ed448_1make_1key
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed448
 * Method:    wc_ed448_make_public
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_wolfcrypt_Ed448_wc_1ed448_1make_1public
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed448
 * Method:    wc_ed448_check_key
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Ed448_wc_1ed448_1check_1key
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed448
 * Method:    ed448_key_privKeySet
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_Ed448_ed448_1key_1privKeySet
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed448
 * Method:    ed448_key_pubKeySet
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_Ed448_ed448_1key_1pubKeySet
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed448
 * Method:    wc_ed448_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_Ed448_wc_1ed448_1size
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed448
 * Method:    wc_ed448_priv_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_Ed448_wc_1ed448_1priv_1size
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed448
 * Method:    wc_ed448_pub_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_Ed448_wc_1ed448_1pub_1size
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed448
 * Method:    wc_ed448_sig_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_Ed448_wc_1ed448_1sig_1size
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed448
 * Method:    wc_ed448_import_private
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Ed448_wc_1ed448_1import_1private
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed448
 * Method:    wc_ed448_import_private_key_ex
 * Signature: ([B[BZ)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Ed448_wc_1ed448_1import_1private_1key_1ex
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jboolean);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed448
 * Method:    wc_ed448_import_private_only
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Ed448_wc_1ed448_1import_1private_1only
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed448
 * Method:    wc_ed448_import_public
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Ed448_wc_1ed448_1import_1public
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed448
 * Method:    wc_ed448_import_public_ex
 * Signature: ([BZ)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Ed448_wc_1ed448_1import_1public_1ex
  (JNIEnv *, jobject, jbyteArray, jboolean);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed448
 * Method:    wc_ed448_export_private
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_wolfcrypt_Ed448_wc_1ed448_1export_1private
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed448
 * Method:    wc_ed448_export_private_only
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_wolfcrypt_Ed448_wc_1ed448_1export_1private_1only
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed448
 * Method:    wc_ed448_export_public
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_wolfcrypt_Ed448_wc_1ed448_1export_1public
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed448
 * Method:    wc_ed448_export_key
 * Signature: ()[[B
 */
JNIEXPORT jobjectArray JNICALL Java_com_wolfssl_wolfcrypt_Ed448_wc_1ed448_1export_1key
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed448
 * Method:    wc_ed448_sign_msg
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_wolfcrypt_Ed448_wc_1ed448_1sign_1msg
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed448
 * Method:    wc_ed448ph_sign_msg
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_wolfcrypt_Ed448_wc_1ed448ph_1sign_1msg
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed448
 * Method:    wc_ed448ph_sign_hash
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_wolfcrypt_Ed448_wc_1ed448ph_1sign_1hash
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed448
 * Method:    wc_ed448_sign_msg_ex
 * Signature: ([BI[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_wolfcrypt_Ed448_wc_1ed448_1sign_1msg_1ex
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed448
 * Method:    wc_ed448_verify_msg
 * Signature: ([B[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_Ed448_wc_1ed448_1verify_1msg
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed448
 * Method:    wc_ed448ph_verify_msg
 * Signature: ([B[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_Ed448_wc_1ed448ph_1verify_1msg
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed448
 * Method:    wc_ed448ph_verify_hash
 * Signature: ([B[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_Ed448_wc_1ed448ph_1verify_1hash
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed448
 * Method:    wc_ed448_verify_msg_ex
 * Signature: ([B[BI[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_Ed448_wc_1ed448_1verify_1msg_1ex
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed448
 * Method:    wc_ed448_verify_msg_init
 * Signature: ([BI[B)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Ed448_wc_1ed448_1verify_1msg_1init
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed448
 * Method:    wc_ed448_verify_msg_update
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Ed448_wc_1ed448_1verify_1msg_1update
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed448
 * Method:    wc_ed448_verify_msg_final
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_Ed448_wc_1ed448_1verify_1msg_1final
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed448
 * Method:    wc_Ed448PublicKeyDecode
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Ed448_wc_1Ed448PublicKeyDecode
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed448
 * Method:    wc_Ed448PrivateKeyDecode
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Ed448_wc_1Ed448PrivateKeyDecode
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed448
 * Method:    wc_Ed448PublicKeyToDer
 * Signature: (Z)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_wolfcrypt_Ed448_wc_1Ed448PublicKeyToDer
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed448
 * Method:    wc_Ed448PrivateKeyToDer
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_wolfcrypt_Ed448_wc_1Ed448PrivateKeyToDer
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed448
 * Method:    wc_Ed448KeyToDer
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_wolfcrypt_Ed448_wc_1Ed448KeyToDer
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
