/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_wolfcrypt_Hmac */

#ifndef _Included_com_wolfssl_wolfcrypt_Hmac
#define _Included_com_wolfssl_wolfcrypt_Hmac
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wolfssl_wolfcrypt_Hmac_NULL
#define com_wolfssl_wolfcrypt_Hmac_NULL 0LL
#undef com_wolfssl_wolfcrypt_Hmac_MD5
#define com_wolfssl_wolfcrypt_Hmac_MD5 0L
#undef com_wolfssl_wolfcrypt_Hmac_SHA
#define com_wolfssl_wolfcrypt_Hmac_SHA 1L
#undef com_wolfssl_wolfcrypt_Hmac_SHA256
#define com_wolfssl_wolfcrypt_Hmac_SHA256 2L
#undef com_wolfssl_wolfcrypt_Hmac_SHA384
#define com_wolfssl_wolfcrypt_Hmac_SHA384 5L
#undef com_wolfssl_wolfcrypt_Hmac_SHA512
#define com_wolfssl_wolfcrypt_Hmac_SHA512 4L
#undef com_wolfssl_wolfcrypt_Hmac_BLAKE2b
#define com_wolfssl_wolfcrypt_Hmac_BLAKE2b 7L
/*
 * Class:     com_wolfssl_wolfcrypt_Hmac
 * Method:    mallocNativeStruct
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_wolfcrypt_Hmac_mallocNativeStruct
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
