/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_wolfcrypt_Shake */

#ifndef _Included_com_wolfssl_wolfcrypt_Shake
#define _Included_com_wolfssl_wolfcrypt_Shake
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wolfssl_wolfcrypt_Shake_NULL
#define com_wolfssl_wolfcrypt_Shake_NULL 0LL
#undef com_wolfssl_wolfcrypt_Shake_DIGEST_SIZE_128
#define com_wolfssl_wolfcrypt_Shake_DIGEST_SIZE_128 32L
#undef com_wolfssl_wolfcrypt_Shake_DIGEST_SIZE_256
#define com_wolfssl_wolfcrypt_Shake_DIGEST_SIZE_256 64L
/*
 * Class:     com_wolfssl_wolfcrypt_Shake
 * Method:    mallocNativeStruct_internal
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_wolfcrypt_Shake_mallocNativeStruct_1internal
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Shake
 * Method:    native_init_internal
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Shake_native_1init_1internal
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_Shake
 * Method:    native_copy_internal
 * Signature: (Lcom/wolfssl/wolfcrypt/Shake;I)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Shake_native_1copy_1internal
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_Shake
 * Method:    native_update_internal
 * Signature: (Ljava/nio/ByteBuffer;III)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Shake_native_1update_1internal__Ljava_nio_ByteBuffer_2III
  (JNIEnv *, jobject, jobject, jint, jint, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_Shake
 * Method:    native_update_internal
 * Signature: ([BIII)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Shake_native_1update_1internal___3BIII
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_Shake
 * Method:    native_final_internal
 * Signature: (Ljava/nio/ByteBuffer;III)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Shake_native_1final_1internal__Ljava_nio_ByteBuffer_2III
  (JNIEnv *, jobject, jobject, jint, jint, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_Shake
 * Method:    native_final_internal
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Shake_native_1final_1internal___3BII
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_Shake
 * Method:    native_free_internal
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Shake_native_1free_1internal
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
