/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_wolfcrypt_Sha384 */

#ifndef _Included_com_wolfssl_wolfcrypt_Sha384
#define _Included_com_wolfssl_wolfcrypt_Sha384
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wolfssl_wolfcrypt_Sha384_NULL
#define com_wolfssl_wolfcrypt_Sha384_NULL 0LL
#undef com_wolfssl_wolfcrypt_Sha384_TYPE
#define com_wolfssl_wolfcrypt_Sha384_TYPE 5L
#undef com_wolfssl_wolfcrypt_Sha384_DIGEST_SIZE
#define com_wolfssl_wolfcrypt_Sha384_DIGEST_SIZE 48L
/*
 * Class:     com_wolfssl_wolfcrypt_Sha384
 * Method:    mallocNativeStruct
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_wolfcrypt_Sha384_mallocNativeStruct
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Sha384
 * Method:    initSha384
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Sha384_initSha384
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Sha384
 * Method:    sha384Update
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Sha384_sha384Update__Ljava_nio_ByteBuffer_2J
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     com_wolfssl_wolfcrypt_Sha384
 * Method:    sha384Update
 * Signature: ([BJ)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Sha384_sha384Update___3BJ
  (JNIEnv *, jobject, jbyteArray, jlong);

/*
 * Class:     com_wolfssl_wolfcrypt_Sha384
 * Method:    sha384Update
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Sha384_sha384Update___3BII
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_Sha384
 * Method:    sha384Final
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Sha384_sha384Final__Ljava_nio_ByteBuffer_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Sha384
 * Method:    sha384Final
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Sha384_sha384Final___3B
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
