/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_wolfcrypt_Des3 */

#ifndef _Included_com_wolfssl_wolfcrypt_Des3
#define _Included_com_wolfssl_wolfcrypt_Des3
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wolfssl_wolfcrypt_Des3_NULL
#define com_wolfssl_wolfcrypt_Des3_NULL 0LL
#undef com_wolfssl_wolfcrypt_Des3_KEY_SIZE
#define com_wolfssl_wolfcrypt_Des3_KEY_SIZE 24L
#undef com_wolfssl_wolfcrypt_Des3_BLOCK_SIZE
#define com_wolfssl_wolfcrypt_Des3_BLOCK_SIZE 8L
#undef com_wolfssl_wolfcrypt_Des3_ENCRYPT_MODE
#define com_wolfssl_wolfcrypt_Des3_ENCRYPT_MODE 0L
#undef com_wolfssl_wolfcrypt_Des3_DECRYPT_MODE
#define com_wolfssl_wolfcrypt_Des3_DECRYPT_MODE 1L
/*
 * Class:     com_wolfssl_wolfcrypt_Des3
 * Method:    mallocNativeStruct
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_wolfcrypt_Des3_mallocNativeStruct
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Des3
 * Method:    native_set_key
 * Signature: ([B[BI)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Des3_native_1set_1key
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_Des3
 * Method:    native_update
 * Signature: (I[BII[BI)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_Des3_native_1update__I_3BII_3BI
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint, jbyteArray, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_Des3
 * Method:    native_update
 * Signature: (ILjava/nio/ByteBuffer;IILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_Des3_native_1update__ILjava_nio_ByteBuffer_2IILjava_nio_ByteBuffer_2I
  (JNIEnv *, jobject, jint, jobject, jint, jint, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
