/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_wolfcrypt_Pwdbased */

#ifndef _Included_com_wolfssl_wolfcrypt_Pwdbased
#define _Included_com_wolfssl_wolfcrypt_Pwdbased
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wolfssl_wolfcrypt_Pwdbased
 * Method:    wc_PKCS12_PBKDF
 * Signature: ([BI[BIIIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_wolfcrypt_Pwdbased_wc_1PKCS12_1PBKDF
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint, jint, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_Pwdbased
 * Method:    wc_PBKDF2
 * Signature: ([BI[BIIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_wolfcrypt_Pwdbased_wc_1PBKDF2
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
