/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_wolfcrypt_AesOfb */

#ifndef _Included_com_wolfssl_wolfcrypt_AesOfb
#define _Included_com_wolfssl_wolfcrypt_AesOfb
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wolfssl_wolfcrypt_AesOfb_NULL
#define com_wolfssl_wolfcrypt_AesOfb_NULL 0LL
#undef com_wolfssl_wolfcrypt_AesOfb_KEY_SIZE_128
#define com_wolfssl_wolfcrypt_AesOfb_KEY_SIZE_128 16L
#undef com_wolfssl_wolfcrypt_AesOfb_KEY_SIZE_192
#define com_wolfssl_wolfcrypt_AesOfb_KEY_SIZE_192 24L
#undef com_wolfssl_wolfcrypt_AesOfb_KEY_SIZE_256
#define com_wolfssl_wolfcrypt_AesOfb_KEY_SIZE_256 32L
#undef com_wolfssl_wolfcrypt_AesOfb_BLOCK_SIZE
#define com_wolfssl_wolfcrypt_AesOfb_BLOCK_SIZE 16L
#undef com_wolfssl_wolfcrypt_AesOfb_ENCRYPT_MODE
#define com_wolfssl_wolfcrypt_AesOfb_ENCRYPT_MODE 0L
#undef com_wolfssl_wolfcrypt_AesOfb_DECRYPT_MODE
#define com_wolfssl_wolfcrypt_AesOfb_DECRYPT_MODE 1L
/*
 * Class:     com_wolfssl_wolfcrypt_AesOfb
 * Method:    mallocNativeStruct_internal
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_wolfcrypt_AesOfb_mallocNativeStruct_1internal
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_AesOfb
 * Method:    native_set_key_internal
 * Signature: ([B[BI)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_AesOfb_native_1set_1key_1internal
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_AesOfb
 * Method:    native_update_internal
 * Signature: (I[BII[BI)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_AesOfb_native_1update_1internal__I_3BII_3BI
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint, jbyteArray, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_AesOfb
 * Method:    native_update_internal
 * Signature: (ILjava/nio/ByteBuffer;IILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_AesOfb_native_1update_1internal__ILjava_nio_ByteBuffer_2IILjava_nio_ByteBuffer_2I
  (JNIEnv *, jobject, jint, jobject, jint, jint, jobject, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_AesOfb
 * Method:    native_encrypt_internal
 * Signature: ([BII[BI)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_AesOfb_native_1encrypt_1internal___3BII_3BI
  (JNIEnv *, jobject, jbyteArray, jint, jint, jbyteArray, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_AesOfb
 * Method:    native_encrypt_internal
 * Signature: (Ljava/nio/ByteBuffer;IILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_AesOfb_native_1encrypt_1internal__Ljava_nio_ByteBuffer_2IILjava_nio_ByteBuffer_2I
  (JNIEnv *, jobject, jobject, jint, jint, jobject, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_AesOfb
 * Method:    native_decrypt_internal
 * Signature: ([BII[BI)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_AesOfb_native_1decrypt_1internal___3BII_3BI
  (JNIEnv *, jobject, jbyteArray, jint, jint, jbyteArray, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_AesOfb
 * Method:    native_decrypt_internal
 * Signature: (Ljava/nio/ByteBuffer;IILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_AesOfb_native_1decrypt_1internal__Ljava_nio_ByteBuffer_2IILjava_nio_ByteBuffer_2I
  (JNIEnv *, jobject, jobject, jint, jint, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
