/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_wolfcrypt_WolfObject */

#ifndef _Included_com_wolfssl_wolfcrypt_WolfObject
#define _Included_com_wolfssl_wolfcrypt_WolfObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wolfssl_wolfcrypt_WolfObject
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_WolfObject_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
