/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_wolfcrypt_Ed25519 */

#ifndef _Included_com_wolfssl_wolfcrypt_Ed25519
#define _Included_com_wolfssl_wolfcrypt_Ed25519
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wolfssl_wolfcrypt_Ed25519_NULL
#define com_wolfssl_wolfcrypt_Ed25519_NULL 0LL
/*
 * Class:     com_wolfssl_wolfcrypt_Ed25519
 * Method:    mallocNativeStruct
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_wolfcrypt_Ed25519_mallocNativeStruct
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed25519
 * Method:    wc_ed25519_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Ed25519_wc_1ed25519_1init
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed25519
 * Method:    wc_ed25519_free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Ed25519_wc_1ed25519_1free
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed25519
 * Method:    wc_ed25519_make_key
 * Signature: (Lcom/wolfssl/wolfcrypt/Rng;I)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Ed25519_wc_1ed25519_1make_1key
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed25519
 * Method:    wc_ed25519_check_key
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Ed25519_wc_1ed25519_1check_1key
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed25519
 * Method:    wc_ed25519_import_private
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Ed25519_wc_1ed25519_1import_1private
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed25519
 * Method:    wc_ed25519_import_private_only
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Ed25519_wc_1ed25519_1import_1private_1only
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed25519
 * Method:    wc_ed25519_import_public
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Ed25519_wc_1ed25519_1import_1public
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed25519
 * Method:    wc_ed25519_sign_msg
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_wolfcrypt_Ed25519_wc_1ed25519_1sign_1msg
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed25519
 * Method:    wc_ed25519_verify_msg
 * Signature: ([B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_Ed25519_wc_1ed25519_1verify_1msg
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed25519
 * Method:    wc_ed25519_export_private
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_wolfcrypt_Ed25519_wc_1ed25519_1export_1private
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed25519
 * Method:    wc_ed25519_export_private_only
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_wolfcrypt_Ed25519_wc_1ed25519_1export_1private_1only
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Ed25519
 * Method:    wc_ed25519_export_public
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_wolfcrypt_Ed25519_wc_1ed25519_1export_1public
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
