/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_wolfcrypt_SlhDsa */

#ifndef _Included_com_wolfssl_wolfcrypt_SlhDsa
#define _Included_com_wolfssl_wolfcrypt_SlhDsa
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wolfssl_wolfcrypt_SlhDsa_NULL
#define com_wolfssl_wolfcrypt_SlhDsa_NULL 0LL
#undef com_wolfssl_wolfcrypt_SlhDsa_SLH_DSA_SHAKE_128S
#define com_wolfssl_wolfcrypt_SlhDsa_SLH_DSA_SHAKE_128S 0L
#undef com_wolfssl_wolfcrypt_SlhDsa_SLH_DSA_SHAKE_128F
#define com_wolfssl_wolfcrypt_SlhDsa_SLH_DSA_SHAKE_128F 1L
#undef com_wolfssl_wolfcrypt_SlhDsa_SLH_DSA_SHAKE_192S
#define com_wolfssl_wolfcrypt_SlhDsa_SLH_DSA_SHAKE_192S 2L
#undef com_wolfssl_wolfcrypt_SlhDsa_SLH_DSA_SHAKE_192F
#define com_wolfssl_wolfcrypt_SlhDsa_SLH_DSA_SHAKE_192F 3L
#undef com_wolfssl_wolfcrypt_SlhDsa_SLH_DSA_SHAKE_256S
#define com_wolfssl_wolfcrypt_SlhDsa_SLH_DSA_SHAKE_256S 4L
#undef com_wolfssl_wolfcrypt_SlhDsa_SLH_DSA_SHAKE_256F
#define com_wolfssl_wolfcrypt_SlhDsa_SLH_DSA_SHAKE_256F 5L
#undef com_wolfssl_wolfcrypt_SlhDsa_SLH_DSA_SHA2_128S
#define com_wolfssl_wolfcrypt_SlhDsa_SLH_DSA_SHA2_128S 6L
#undef com_wolfssl_wolfcrypt_SlhDsa_SLH_DSA_SHA2_128F
#define com_wolfssl_wolfcrypt_SlhDsa_SLH_DSA_SHA2_128F 7L
#undef com_wolfssl_wolfcrypt_SlhDsa_SLH_DSA_SHA2_192S
#define com_wolfssl_wolfcrypt_SlhDsa_SLH_DSA_SHA2_192S 8L
#undef com_wolfssl_wolfcrypt_SlhDsa_SLH_DSA_SHA2_192F
#define com_wolfssl_wolfcrypt_SlhDsa_SLH_DSA_SHA2_192F 9L
#undef com_wolfssl_wolfcrypt_SlhDsa_SLH_DSA_SHA2_256S
#define com_wolfssl_wolfcrypt_SlhDsa_SLH_DSA_SHA2_256S 10L
#undef com_wolfssl_wolfcrypt_SlhDsa_SLH_DSA_SHA2_256F
#define com_wolfssl_wolfcrypt_SlhDsa_SLH_DSA_SHA2_256F 11L
#undef com_wolfssl_wolfcrypt_SlhDsa_SLH_DSA_MAX_CONTEXT_LEN
#define com_wolfssl_wolfcrypt_SlhDsa_SLH_DSA_MAX_CONTEXT_LEN 255L
#undef com_wolfssl_wolfcrypt_SlhDsa_PARAM_MIN
#define com_wolfssl_wolfcrypt_SlhDsa_PARAM_MIN 0L
#undef com_wolfssl_wolfcrypt_SlhDsa_PARAM_MAX
#define com_wolfssl_wolfcrypt_SlhDsa_PARAM_MAX 11L
#undef com_wolfssl_wolfcrypt_SlhDsa_PARAM_UNSET
#define com_wolfssl_wolfcrypt_SlhDsa_PARAM_UNSET -1L
/*
 * Class:     com_wolfssl_wolfcrypt_SlhDsa
 * Method:    mallocNativeStruct
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_wolfcrypt_SlhDsa_mallocNativeStruct
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_SlhDsa
 * Method:    wc_SlhDsaKey_init
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_SlhDsa_wc_1SlhDsaKey_1init
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_SlhDsa
 * Method:    wc_SlhDsaKey_free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_SlhDsa_wc_1SlhDsaKey_1free
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_SlhDsa
 * Method:    wc_SlhDsaKey_get_param
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_SlhDsa_wc_1SlhDsaKey_1get_1param
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_SlhDsa
 * Method:    wc_SlhDsaKey_make_key
 * Signature: (Lcom/wolfssl/wolfcrypt/Rng;)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_SlhDsa_wc_1SlhDsaKey_1make_1key
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_SlhDsa
 * Method:    wc_SlhDsaKey_make_key_with_seeds
 * Signature: ([B[B[B)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_SlhDsa_wc_1SlhDsaKey_1make_1key_1with_1seeds
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_SlhDsa
 * Method:    wc_SlhDsaKey_sign
 * Signature: ([B[BLcom/wolfssl/wolfcrypt/Rng;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_wolfcrypt_SlhDsa_wc_1SlhDsaKey_1sign
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_SlhDsa
 * Method:    wc_SlhDsaKey_sign_deterministic
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_wolfcrypt_SlhDsa_wc_1SlhDsaKey_1sign_1deterministic
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_SlhDsa
 * Method:    wc_SlhDsaKey_sign_hash
 * Signature: ([BI[BLcom/wolfssl/wolfcrypt/Rng;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_wolfcrypt_SlhDsa_wc_1SlhDsaKey_1sign_1hash
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_SlhDsa
 * Method:    wc_SlhDsaKey_sign_msg_prehash
 * Signature: ([B[BLcom/wolfssl/wolfcrypt/Rng;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_wolfcrypt_SlhDsa_wc_1SlhDsaKey_1sign_1msg_1prehash
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_SlhDsa
 * Method:    wc_SlhDsaKey_verify
 * Signature: ([B[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_SlhDsa_wc_1SlhDsaKey_1verify
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_SlhDsa
 * Method:    wc_SlhDsaKey_verify_hash
 * Signature: ([B[BI[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_SlhDsa_wc_1SlhDsaKey_1verify_1hash
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_SlhDsa
 * Method:    wc_SlhDsaKey_verify_msg_prehash
 * Signature: ([B[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_SlhDsa_wc_1SlhDsaKey_1verify_1msg_1prehash
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_SlhDsa
 * Method:    wc_SlhDsaKey_export_public
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_wolfcrypt_SlhDsa_wc_1SlhDsaKey_1export_1public
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_SlhDsa
 * Method:    wc_SlhDsaKey_export_private
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_wolfcrypt_SlhDsa_wc_1SlhDsaKey_1export_1private
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_SlhDsa
 * Method:    wc_SlhDsaKey_import_public
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_SlhDsa_wc_1SlhDsaKey_1import_1public
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_SlhDsa
 * Method:    wc_SlhDsaKey_import_private
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_SlhDsa_wc_1SlhDsaKey_1import_1private
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_SlhDsa
 * Method:    wc_SlhDsaKey_PublicKeyToDer
 * Signature: (Z)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_wolfcrypt_SlhDsa_wc_1SlhDsaKey_1PublicKeyToDer
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wolfssl_wolfcrypt_SlhDsa
 * Method:    wc_SlhDsaKey_KeyToDer
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_wolfcrypt_SlhDsa_wc_1SlhDsaKey_1KeyToDer
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_SlhDsa
 * Method:    wc_SlhDsaKey_PublicKeyDecode
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_SlhDsa_wc_1SlhDsaKey_1PublicKeyDecode
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_SlhDsa
 * Method:    wc_SlhDsaKey_PrivateKeyDecode
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_SlhDsa_wc_1SlhDsaKey_1PrivateKeyDecode
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_SlhDsa
 * Method:    wc_SlhDsaKey_pub_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_SlhDsa_wc_1SlhDsaKey_1pub_1size
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_SlhDsa
 * Method:    wc_SlhDsaKey_priv_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_SlhDsa_wc_1SlhDsaKey_1priv_1size
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_SlhDsa
 * Method:    wc_SlhDsaKey_sig_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_SlhDsa_wc_1SlhDsaKey_1sig_1size
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_SlhDsa
 * Method:    wc_SlhDsaKey_check_key
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_SlhDsa_wc_1SlhDsaKey_1check_1key
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
