/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_wolfcrypt_Sha256 */

#ifndef _Included_com_wolfssl_wolfcrypt_Sha256
#define _Included_com_wolfssl_wolfcrypt_Sha256
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wolfssl_wolfcrypt_Sha256_NULL
#define com_wolfssl_wolfcrypt_Sha256_NULL 0LL
#undef com_wolfssl_wolfcrypt_Sha256_TYPE
#define com_wolfssl_wolfcrypt_Sha256_TYPE 2L
#undef com_wolfssl_wolfcrypt_Sha256_DIGEST_SIZE
#define com_wolfssl_wolfcrypt_Sha256_DIGEST_SIZE 32L
/*
 * Class:     com_wolfssl_wolfcrypt_Sha256
 * Method:    mallocNativeStruct
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_wolfcrypt_Sha256_mallocNativeStruct
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
