/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_wolfcrypt_Sha384 */

#ifndef _Included_com_wolfssl_wolfcrypt_Sha384
#define _Included_com_wolfssl_wolfcrypt_Sha384
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wolfssl_wolfcrypt_Sha384_NULL
#define com_wolfssl_wolfcrypt_Sha384_NULL 0LL
#undef com_wolfssl_wolfcrypt_Sha384_TYPE
#define com_wolfssl_wolfcrypt_Sha384_TYPE 5L
#undef com_wolfssl_wolfcrypt_Sha384_DIGEST_SIZE
#define com_wolfssl_wolfcrypt_Sha384_DIGEST_SIZE 48L
/*
 * Class:     com_wolfssl_wolfcrypt_Sha384
 * Method:    mallocNativeStruct
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_wolfcrypt_Sha384_mallocNativeStruct
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
