/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_wolfcrypt_NativeStruct */

#ifndef _Included_com_wolfssl_wolfcrypt_NativeStruct
#define _Included_com_wolfssl_wolfcrypt_NativeStruct
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wolfssl_wolfcrypt_NativeStruct_NULL
#define com_wolfssl_wolfcrypt_NativeStruct_NULL 0LL
/*
 * Class:     com_wolfssl_wolfcrypt_NativeStruct
 * Method:    xfree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_NativeStruct_xfree
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
