/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_wolfcrypt_Hmac_hashType */

#ifndef _Included_com_wolfssl_wolfcrypt_Hmac_hashType
#define _Included_com_wolfssl_wolfcrypt_Hmac_hashType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
