/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_wolfcrypt_Dh */

#ifndef _Included_com_wolfssl_wolfcrypt_Dh
#define _Included_com_wolfssl_wolfcrypt_Dh
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wolfssl_wolfcrypt_Dh_NULL
#define com_wolfssl_wolfcrypt_Dh_NULL 0LL
#undef com_wolfssl_wolfcrypt_Dh_WC_FFDHE_2048
#define com_wolfssl_wolfcrypt_Dh_WC_FFDHE_2048 256L
#undef com_wolfssl_wolfcrypt_Dh_WC_FFDHE_3072
#define com_wolfssl_wolfcrypt_Dh_WC_FFDHE_3072 257L
#undef com_wolfssl_wolfcrypt_Dh_WC_FFDHE_4096
#define com_wolfssl_wolfcrypt_Dh_WC_FFDHE_4096 258L
#undef com_wolfssl_wolfcrypt_Dh_WC_FFDHE_6144
#define com_wolfssl_wolfcrypt_Dh_WC_FFDHE_6144 259L
#undef com_wolfssl_wolfcrypt_Dh_WC_FFDHE_8192
#define com_wolfssl_wolfcrypt_Dh_WC_FFDHE_8192 260L
/*
 * Class:     com_wolfssl_wolfcrypt_Dh
 * Method:    mallocNativeStruct_internal
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_wolfcrypt_Dh_mallocNativeStruct_1internal
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Dh
 * Method:    wc_InitDhKey
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Dh_wc_1InitDhKey
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Dh
 * Method:    wc_FreeDhKey
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Dh_wc_1FreeDhKey
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Dh
 * Method:    wc_DhSetKey
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Dh_wc_1DhSetKey
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_Dh
 * Method:    wc_DhGenerateKeyPair
 * Signature: (Lcom/wolfssl/wolfcrypt/Rng;I)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Dh_wc_1DhGenerateKeyPair
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_Dh
 * Method:    wc_DhAgree
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_wolfcrypt_Dh_wc_1DhAgree
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_Dh
 * Method:    wc_DhCheckPubKey
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Dh_wc_1DhCheckPubKey
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_Dh
 * Method:    wc_DhCopyNamedKey
 * Signature: (I)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_com_wolfssl_wolfcrypt_Dh_wc_1DhCopyNamedKey
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_Dh
 * Method:    wc_DhGenerateParams
 * Signature: (Lcom/wolfssl/wolfcrypt/Rng;I)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_com_wolfssl_wolfcrypt_Dh_wc_1DhGenerateParams
  (JNIEnv *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
