/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_wolfcrypt_AesCfb */

#ifndef _Included_com_wolfssl_wolfcrypt_AesCfb
#define _Included_com_wolfssl_wolfcrypt_AesCfb
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wolfssl_wolfcrypt_AesCfb_NULL
#define com_wolfssl_wolfcrypt_AesCfb_NULL 0LL
#undef com_wolfssl_wolfcrypt_AesCfb_KEY_SIZE_128
#define com_wolfssl_wolfcrypt_AesCfb_KEY_SIZE_128 16L
#undef com_wolfssl_wolfcrypt_AesCfb_KEY_SIZE_192
#define com_wolfssl_wolfcrypt_AesCfb_KEY_SIZE_192 24L
#undef com_wolfssl_wolfcrypt_AesCfb_KEY_SIZE_256
#define com_wolfssl_wolfcrypt_AesCfb_KEY_SIZE_256 32L
#undef com_wolfssl_wolfcrypt_AesCfb_BLOCK_SIZE
#define com_wolfssl_wolfcrypt_AesCfb_BLOCK_SIZE 16L
#undef com_wolfssl_wolfcrypt_AesCfb_ENCRYPT_MODE
#define com_wolfssl_wolfcrypt_AesCfb_ENCRYPT_MODE 0L
#undef com_wolfssl_wolfcrypt_AesCfb_DECRYPT_MODE
#define com_wolfssl_wolfcrypt_AesCfb_DECRYPT_MODE 1L
#undef com_wolfssl_wolfcrypt_AesCfb_CFB_MODE_128
#define com_wolfssl_wolfcrypt_AesCfb_CFB_MODE_128 128L
#undef com_wolfssl_wolfcrypt_AesCfb_CFB_MODE_8
#define com_wolfssl_wolfcrypt_AesCfb_CFB_MODE_8 8L
#undef com_wolfssl_wolfcrypt_AesCfb_CFB_MODE_1
#define com_wolfssl_wolfcrypt_AesCfb_CFB_MODE_1 1L
/*
 * Class:     com_wolfssl_wolfcrypt_AesCfb
 * Method:    mallocNativeStruct_internal
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_wolfcrypt_AesCfb_mallocNativeStruct_1internal
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_AesCfb
 * Method:    wc_AesInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_AesCfb_wc_1AesInit
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_AesCfb
 * Method:    wc_AesFree
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_AesCfb_wc_1AesFree
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_AesCfb
 * Method:    native_set_key_internal
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_AesCfb_native_1set_1key_1internal
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_AesCfb
 * Method:    native_update_internal
 * Signature: (II[BII[BI)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_AesCfb_native_1update_1internal__II_3BII_3BI
  (JNIEnv *, jobject, jint, jint, jbyteArray, jint, jint, jbyteArray, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_AesCfb
 * Method:    native_update_internal
 * Signature: (IILjava/nio/ByteBuffer;IILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_AesCfb_native_1update_1internal__IILjava_nio_ByteBuffer_2IILjava_nio_ByteBuffer_2I
  (JNIEnv *, jobject, jint, jint, jobject, jint, jint, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
