/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_wolfcrypt_Md5 */

#ifndef _Included_com_wolfssl_wolfcrypt_Md5
#define _Included_com_wolfssl_wolfcrypt_Md5
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wolfssl_wolfcrypt_Md5_NULL
#define com_wolfssl_wolfcrypt_Md5_NULL 0LL
#undef com_wolfssl_wolfcrypt_Md5_TYPE
#define com_wolfssl_wolfcrypt_Md5_TYPE 0L
#undef com_wolfssl_wolfcrypt_Md5_DIGEST_SIZE
#define com_wolfssl_wolfcrypt_Md5_DIGEST_SIZE 16L
/*
 * Class:     com_wolfssl_wolfcrypt_Md5
 * Method:    mallocNativeStruct
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_wolfcrypt_Md5_mallocNativeStruct
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
