/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_wolfcrypt_WolfCryptError */

#ifndef _Included_com_wolfssl_wolfcrypt_WolfCryptError
#define _Included_com_wolfssl_wolfcrypt_WolfCryptError
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wolfssl_wolfcrypt_WolfCryptError
 * Method:    wc_GetErrorString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wolfssl_wolfcrypt_WolfCryptError_wc_1GetErrorString
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
