/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_wolfcrypt_Logging */

#ifndef _Included_com_wolfssl_wolfcrypt_Logging
#define _Included_com_wolfssl_wolfcrypt_Logging
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wolfssl_wolfcrypt_Logging
 * Method:    wolfSSL_Debugging_ON
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_Logging_wolfSSL_1Debugging_1ON
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_Logging
 * Method:    wolfSSL_Debugging_OFF
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Logging_wolfSSL_1Debugging_1OFF
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
