/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_wolfcrypt_AesCmac */

#ifndef _Included_com_wolfssl_wolfcrypt_AesCmac
#define _Included_com_wolfssl_wolfcrypt_AesCmac
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wolfssl_wolfcrypt_AesCmac_NULL
#define com_wolfssl_wolfcrypt_AesCmac_NULL 0LL
/*
 * Class:     com_wolfssl_wolfcrypt_AesCmac
 * Method:    mallocNativeStruct_internal
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_wolfcrypt_AesCmac_mallocNativeStruct_1internal
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_AesCmac
 * Method:    native_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_AesCmac_native_1init
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_AesCmac
 * Method:    native_free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_AesCmac_native_1free
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_AesCmac
 * Method:    wc_CmacSetKey
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_AesCmac_wc_1CmacSetKey
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_AesCmac
 * Method:    wc_CmacUpdate
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_AesCmac_wc_1CmacUpdate__B
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     com_wolfssl_wolfcrypt_AesCmac
 * Method:    wc_CmacUpdate
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_AesCmac_wc_1CmacUpdate___3BII
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_AesCmac
 * Method:    wc_CmacUpdate
 * Signature: (Ljava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_AesCmac_wc_1CmacUpdate__Ljava_nio_ByteBuffer_2II
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_AesCmac
 * Method:    wc_CmacFinal
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_wolfcrypt_AesCmac_wc_1CmacFinal
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_AesCmac
 * Method:    wc_AesCmacGenerate
 * Signature: ([BI[BI[BI)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_AesCmac_wc_1AesCmacGenerate
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_AesCmac
 * Method:    wc_AesCmacVerify
 * Signature: ([BI[BI[BI)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_AesCmac_wc_1AesCmacVerify
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
