/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_wolfcrypt_Sha3 */

#ifndef _Included_com_wolfssl_wolfcrypt_Sha3
#define _Included_com_wolfssl_wolfcrypt_Sha3
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wolfssl_wolfcrypt_Sha3_NULL
#define com_wolfssl_wolfcrypt_Sha3_NULL 0LL
#undef com_wolfssl_wolfcrypt_Sha3_TYPE_SHA3_224
#define com_wolfssl_wolfcrypt_Sha3_TYPE_SHA3_224 10L
#undef com_wolfssl_wolfcrypt_Sha3_TYPE_SHA3_256
#define com_wolfssl_wolfcrypt_Sha3_TYPE_SHA3_256 11L
#undef com_wolfssl_wolfcrypt_Sha3_TYPE_SHA3_384
#define com_wolfssl_wolfcrypt_Sha3_TYPE_SHA3_384 12L
#undef com_wolfssl_wolfcrypt_Sha3_TYPE_SHA3_512
#define com_wolfssl_wolfcrypt_Sha3_TYPE_SHA3_512 13L
#undef com_wolfssl_wolfcrypt_Sha3_DIGEST_SIZE_224
#define com_wolfssl_wolfcrypt_Sha3_DIGEST_SIZE_224 28L
#undef com_wolfssl_wolfcrypt_Sha3_DIGEST_SIZE_256
#define com_wolfssl_wolfcrypt_Sha3_DIGEST_SIZE_256 32L
#undef com_wolfssl_wolfcrypt_Sha3_DIGEST_SIZE_384
#define com_wolfssl_wolfcrypt_Sha3_DIGEST_SIZE_384 48L
#undef com_wolfssl_wolfcrypt_Sha3_DIGEST_SIZE_512
#define com_wolfssl_wolfcrypt_Sha3_DIGEST_SIZE_512 64L
/*
 * Class:     com_wolfssl_wolfcrypt_Sha3
 * Method:    mallocNativeStruct_internal
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_wolfcrypt_Sha3_mallocNativeStruct_1internal
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Sha3
 * Method:    native_init_internal
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Sha3_native_1init_1internal
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_Sha3
 * Method:    native_copy_internal
 * Signature: (Lcom/wolfssl/wolfcrypt/Sha3;I)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Sha3_native_1copy_1internal
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_Sha3
 * Method:    native_update_internal
 * Signature: (Ljava/nio/ByteBuffer;III)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Sha3_native_1update_1internal__Ljava_nio_ByteBuffer_2III
  (JNIEnv *, jobject, jobject, jint, jint, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_Sha3
 * Method:    native_update_internal
 * Signature: ([BIII)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Sha3_native_1update_1internal___3BIII
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_Sha3
 * Method:    native_final_internal
 * Signature: (Ljava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Sha3_native_1final_1internal__Ljava_nio_ByteBuffer_2II
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_Sha3
 * Method:    native_final_internal
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Sha3_native_1final_1internal___3BI
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
