/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_wolfcrypt_FeatureDetect */

#ifndef _Included_com_wolfssl_wolfcrypt_FeatureDetect
#define _Included_com_wolfssl_wolfcrypt_FeatureDetect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    Md5Enabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_Md5Enabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    ShaEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_ShaEnabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    Sha256Enabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_Sha256Enabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    Sha384Enabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_Sha384Enabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    Sha512Enabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_Sha512Enabled
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
