/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_wolfcrypt_Sha512 */

#ifndef _Included_com_wolfssl_wolfcrypt_Sha512
#define _Included_com_wolfssl_wolfcrypt_Sha512
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wolfssl_wolfcrypt_Sha512_NULL
#define com_wolfssl_wolfcrypt_Sha512_NULL 0LL
#undef com_wolfssl_wolfcrypt_Sha512_TYPE
#define com_wolfssl_wolfcrypt_Sha512_TYPE 4L
#undef com_wolfssl_wolfcrypt_Sha512_DIGEST_SIZE
#define com_wolfssl_wolfcrypt_Sha512_DIGEST_SIZE 64L
/*
 * Class:     com_wolfssl_wolfcrypt_Sha512
 * Method:    mallocNativeStruct
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_wolfcrypt_Sha512_mallocNativeStruct
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Sha512
 * Method:    initSha512
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Sha512_initSha512
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Sha512
 * Method:    sha512Update
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Sha512_sha512Update__Ljava_nio_ByteBuffer_2J
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     com_wolfssl_wolfcrypt_Sha512
 * Method:    sha512Update
 * Signature: ([BJ)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Sha512_sha512Update___3BJ
  (JNIEnv *, jobject, jbyteArray, jlong);

/*
 * Class:     com_wolfssl_wolfcrypt_Sha512
 * Method:    sha512Update
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Sha512_sha512Update___3BII
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_Sha512
 * Method:    sha512Final
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Sha512_sha512Final__Ljava_nio_ByteBuffer_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Sha512
 * Method:    sha512Final
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Sha512_sha512Final___3B
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
