/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_wolfcrypt_WolfCrypt */

#ifndef _Included_com_wolfssl_wolfcrypt_WolfCrypt
#define _Included_com_wolfssl_wolfcrypt_WolfCrypt
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wolfssl_wolfcrypt_WolfCrypt_SUCCESS
#define com_wolfssl_wolfcrypt_WolfCrypt_SUCCESS 0L
#undef com_wolfssl_wolfcrypt_WolfCrypt_FAILURE
#define com_wolfssl_wolfcrypt_WolfCrypt_FAILURE -1L
#undef com_wolfssl_wolfcrypt_WolfCrypt_WOLFSSL_SUCCESS
#define com_wolfssl_wolfcrypt_WolfCrypt_WOLFSSL_SUCCESS 1L
#undef com_wolfssl_wolfcrypt_WolfCrypt_SIZE_OF_128_BITS
#define com_wolfssl_wolfcrypt_WolfCrypt_SIZE_OF_128_BITS 16L
#undef com_wolfssl_wolfcrypt_WolfCrypt_SIZE_OF_160_BITS
#define com_wolfssl_wolfcrypt_WolfCrypt_SIZE_OF_160_BITS 20L
#undef com_wolfssl_wolfcrypt_WolfCrypt_SIZE_OF_192_BITS
#define com_wolfssl_wolfcrypt_WolfCrypt_SIZE_OF_192_BITS 24L
#undef com_wolfssl_wolfcrypt_WolfCrypt_SIZE_OF_256_BITS
#define com_wolfssl_wolfcrypt_WolfCrypt_SIZE_OF_256_BITS 32L
#undef com_wolfssl_wolfcrypt_WolfCrypt_SIZE_OF_384_BITS
#define com_wolfssl_wolfcrypt_WolfCrypt_SIZE_OF_384_BITS 48L
#undef com_wolfssl_wolfcrypt_WolfCrypt_SIZE_OF_512_BITS
#define com_wolfssl_wolfcrypt_WolfCrypt_SIZE_OF_512_BITS 64L
#undef com_wolfssl_wolfcrypt_WolfCrypt_SIZE_OF_1024_BITS
#define com_wolfssl_wolfcrypt_WolfCrypt_SIZE_OF_1024_BITS 128L
#undef com_wolfssl_wolfcrypt_WolfCrypt_SIZE_OF_2048_BITS
#define com_wolfssl_wolfcrypt_WolfCrypt_SIZE_OF_2048_BITS 256L
/*
 * Class:     com_wolfssl_wolfcrypt_WolfCrypt
 * Method:    CrlEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_WolfCrypt_CrlEnabled
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
