/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_wolfcrypt_Xmss */

#ifndef _Included_com_wolfssl_wolfcrypt_Xmss
#define _Included_com_wolfssl_wolfcrypt_Xmss
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wolfssl_wolfcrypt_Xmss_NULL
#define com_wolfssl_wolfcrypt_Xmss_NULL 0LL
/*
 * Class:     com_wolfssl_wolfcrypt_Xmss
 * Method:    mallocNativeStruct
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_wolfcrypt_Xmss_mallocNativeStruct
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Xmss
 * Method:    wc_XmssKey_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Xmss_wc_1XmssKey_1init
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Xmss
 * Method:    wc_XmssKey_free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Xmss_wc_1XmssKey_1free
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Xmss
 * Method:    wc_XmssKey_get_param_str
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wolfssl_wolfcrypt_Xmss_wc_1XmssKey_1get_1param_1str
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Xmss
 * Method:    wc_XmssKey_verify
 * Signature: ([B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_Xmss_wc_1XmssKey_1verify
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_Xmss
 * Method:    wc_XmssKey_import_public
 * Signature: ([BZ)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Xmss_wc_1XmssKey_1import_1public
  (JNIEnv *, jobject, jbyteArray, jboolean);

#ifdef __cplusplus
}
#endif
#endif
