/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_wolfcrypt_MlDsa */

#ifndef _Included_com_wolfssl_wolfcrypt_MlDsa
#define _Included_com_wolfssl_wolfcrypt_MlDsa
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wolfssl_wolfcrypt_MlDsa_NULL
#define com_wolfssl_wolfcrypt_MlDsa_NULL 0LL
#undef com_wolfssl_wolfcrypt_MlDsa_ML_DSA_44
#define com_wolfssl_wolfcrypt_MlDsa_ML_DSA_44 2L
#undef com_wolfssl_wolfcrypt_MlDsa_ML_DSA_65
#define com_wolfssl_wolfcrypt_MlDsa_ML_DSA_65 3L
#undef com_wolfssl_wolfcrypt_MlDsa_ML_DSA_87
#define com_wolfssl_wolfcrypt_MlDsa_ML_DSA_87 5L
#undef com_wolfssl_wolfcrypt_MlDsa_ML_DSA_MAX_CTX_LEN
#define com_wolfssl_wolfcrypt_MlDsa_ML_DSA_MAX_CTX_LEN 255L
#undef com_wolfssl_wolfcrypt_MlDsa_ML_DSA_SEED_LEN
#define com_wolfssl_wolfcrypt_MlDsa_ML_DSA_SEED_LEN 32L
#undef com_wolfssl_wolfcrypt_MlDsa_ML_DSA_RND_LEN
#define com_wolfssl_wolfcrypt_MlDsa_ML_DSA_RND_LEN 32L
#undef com_wolfssl_wolfcrypt_MlDsa_ML_DSA_MU_LEN
#define com_wolfssl_wolfcrypt_MlDsa_ML_DSA_MU_LEN 64L
#undef com_wolfssl_wolfcrypt_MlDsa_LEVEL_UNSET
#define com_wolfssl_wolfcrypt_MlDsa_LEVEL_UNSET 0L
/*
 * Class:     com_wolfssl_wolfcrypt_MlDsa
 * Method:    mallocNativeStruct
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_wolfcrypt_MlDsa_mallocNativeStruct
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_MlDsa
 * Method:    wc_dilithium_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_MlDsa_wc_1dilithium_1init
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_MlDsa
 * Method:    wc_dilithium_free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_MlDsa_wc_1dilithium_1free
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_MlDsa
 * Method:    wc_dilithium_set_level
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_MlDsa_wc_1dilithium_1set_1level
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_MlDsa
 * Method:    wc_dilithium_get_level
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_MlDsa_wc_1dilithium_1get_1level
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_MlDsa
 * Method:    wc_dilithium_make_key
 * Signature: (Lcom/wolfssl/wolfcrypt/Rng;)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_MlDsa_wc_1dilithium_1make_1key
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_MlDsa
 * Method:    wc_dilithium_sign_ctx_msg
 * Signature: ([B[BLcom/wolfssl/wolfcrypt/Rng;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_wolfcrypt_MlDsa_wc_1dilithium_1sign_1ctx_1msg
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_MlDsa
 * Method:    wc_dilithium_verify_ctx_msg
 * Signature: ([B[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_MlDsa_wc_1dilithium_1verify_1ctx_1msg
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_MlDsa
 * Method:    wc_dilithium_export_public
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_wolfcrypt_MlDsa_wc_1dilithium_1export_1public
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_MlDsa
 * Method:    wc_dilithium_export_private
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_wolfcrypt_MlDsa_wc_1dilithium_1export_1private
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_MlDsa
 * Method:    wc_dilithium_import_public
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_MlDsa_wc_1dilithium_1import_1public
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_MlDsa
 * Method:    wc_dilithium_import_private
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_MlDsa_wc_1dilithium_1import_1private
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_MlDsa
 * Method:    wc_Dilithium_PublicKeyToDer
 * Signature: (Z)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_wolfcrypt_MlDsa_wc_1Dilithium_1PublicKeyToDer
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wolfssl_wolfcrypt_MlDsa
 * Method:    wc_Dilithium_KeyToDer
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_wolfcrypt_MlDsa_wc_1Dilithium_1KeyToDer
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_MlDsa
 * Method:    wc_Dilithium_PublicKeyDecode
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_MlDsa_wc_1Dilithium_1PublicKeyDecode
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_MlDsa
 * Method:    wc_Dilithium_PrivateKeyDecode
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_MlDsa_wc_1Dilithium_1PrivateKeyDecode
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_MlDsa
 * Method:    wc_dilithium_pub_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_MlDsa_wc_1dilithium_1pub_1size
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_MlDsa
 * Method:    wc_dilithium_priv_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_MlDsa_wc_1dilithium_1priv_1size
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_MlDsa
 * Method:    wc_dilithium_sig_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_MlDsa_wc_1dilithium_1sig_1size
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_MlDsa
 * Method:    wc_dilithium_make_key_from_seed
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_MlDsa_wc_1dilithium_1make_1key_1from_1seed
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_MlDsa
 * Method:    wc_dilithium_sign_ctx_hash
 * Signature: ([BI[BLcom/wolfssl/wolfcrypt/Rng;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_wolfcrypt_MlDsa_wc_1dilithium_1sign_1ctx_1hash
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_MlDsa
 * Method:    wc_dilithium_sign_ctx_msg_with_seed
 * Signature: ([B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_wolfcrypt_MlDsa_wc_1dilithium_1sign_1ctx_1msg_1with_1seed
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_MlDsa
 * Method:    wc_dilithium_sign_ctx_hash_with_seed
 * Signature: ([BI[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_wolfcrypt_MlDsa_wc_1dilithium_1sign_1ctx_1hash_1with_1seed
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_MlDsa
 * Method:    wc_dilithium_verify_ctx_hash
 * Signature: ([B[BI[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_MlDsa_wc_1dilithium_1verify_1ctx_1hash
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_MlDsa
 * Method:    wc_MlDsaKey_SignMuWithSeed
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_wolfcrypt_MlDsa_wc_1MlDsaKey_1SignMuWithSeed
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_MlDsa
 * Method:    wc_MlDsaKey_VerifyMu
 * Signature: ([B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_MlDsa_wc_1MlDsaKey_1VerifyMu
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_MlDsa
 * Method:    wc_dilithium_import_key
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_MlDsa_wc_1dilithium_1import_1key
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_MlDsa
 * Method:    wc_dilithium_check_key
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_MlDsa_wc_1dilithium_1check_1key
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_MlDsa
 * Method:    wc_Dilithium_PrivateKeyToDer
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_wolfcrypt_MlDsa_wc_1Dilithium_1PrivateKeyToDer
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
