/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_wolfcrypt_FeatureDetect */

#ifndef _Included_com_wolfssl_wolfcrypt_FeatureDetect
#define _Included_com_wolfssl_wolfcrypt_FeatureDetect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    Md5Enabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_Md5Enabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    ShaEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_ShaEnabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    Sha224Enabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_Sha224Enabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    Sha256Enabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_Sha256Enabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    Sha384Enabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_Sha384Enabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    Sha512Enabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_Sha512Enabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    Sha3Enabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_Sha3Enabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    AesEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_AesEnabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    Aes128Enabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_Aes128Enabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    Aes192Enabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_Aes192Enabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    Aes256Enabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_Aes256Enabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    AesCbcEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_AesCbcEnabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    AesGcmEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_AesGcmEnabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    AesGcmStreamEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_AesGcmStreamEnabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    Des3Enabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_Des3Enabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    ChaChaEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_ChaChaEnabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    HmacEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_HmacEnabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    HmacMd5Enabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_HmacMd5Enabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    HmacShaEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_HmacShaEnabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    HmacSha224Enabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_HmacSha224Enabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    HmacSha256Enabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_HmacSha256Enabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    HmacSha384Enabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_HmacSha384Enabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    HmacSha512Enabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_HmacSha512Enabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    HmacSha3_224Enabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_HmacSha3_1224Enabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    HmacSha3_256Enabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_HmacSha3_1256Enabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    HmacSha3_384Enabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_HmacSha3_1384Enabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    HmacSha3_512Enabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_HmacSha3_1512Enabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    Pbkdf1Enabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_Pbkdf1Enabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    Pbkdf2Enabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_Pbkdf2Enabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    Pkcs12PbkdfEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_Pkcs12PbkdfEnabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    RsaEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_RsaEnabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    RsaKeyGenEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_RsaKeyGenEnabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    RsaPssEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_RsaPssEnabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    DhEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_DhEnabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    EccEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_EccEnabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    EccKeyGenEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_EccKeyGenEnabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    EccDheEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_EccDheEnabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    Curve25519Enabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_Curve25519Enabled
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_FeatureDetect
 * Method:    Ed25519Enabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wolfssl_wolfcrypt_FeatureDetect_Ed25519Enabled
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
