/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_wolfcrypt_Dh */

#ifndef _Included_com_wolfssl_wolfcrypt_Dh
#define _Included_com_wolfssl_wolfcrypt_Dh
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wolfssl_wolfcrypt_Dh_NULL
#define com_wolfssl_wolfcrypt_Dh_NULL 0LL
/*
 * Class:     com_wolfssl_wolfcrypt_Dh
 * Method:    mallocNativeStruct
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_wolfcrypt_Dh_mallocNativeStruct
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
