/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_wolfcrypt_WolfSSLX509StoreCtx */

#ifndef _Included_com_wolfssl_wolfcrypt_WolfSSLX509StoreCtx
#define _Included_com_wolfssl_wolfcrypt_WolfSSLX509StoreCtx
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wolfssl_wolfcrypt_WolfSSLX509StoreCtx
 * Method:    wolfSSL_X509_STORE_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_wolfcrypt_WolfSSLX509StoreCtx_wolfSSL_1X509_1STORE_1new
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_WolfSSLX509StoreCtx
 * Method:    wolfSSL_X509_STORE_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_WolfSSLX509StoreCtx_wolfSSL_1X509_1STORE_1free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_wolfssl_wolfcrypt_WolfSSLX509StoreCtx
 * Method:    wolfSSL_X509_STORE_add_cert
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_WolfSSLX509StoreCtx_wolfSSL_1X509_1STORE_1add_1cert
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_WolfSSLX509StoreCtx
 * Method:    wolfSSL_X509_verify_cert_and_get_chain
 * Signature: (J[B[[BI)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_com_wolfssl_wolfcrypt_WolfSSLX509StoreCtx_wolfSSL_1X509_1verify_1cert_1and_1get_1chain
  (JNIEnv *, jclass, jlong, jbyteArray, jobjectArray, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_WolfSSLX509StoreCtx
 * Method:    isCertPathBuilderSupported
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_WolfSSLX509StoreCtx_isCertPathBuilderSupported
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
