/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_wolfcrypt_Des3 */

#ifndef _Included_com_wolfssl_wolfcrypt_Des3
#define _Included_com_wolfssl_wolfcrypt_Des3
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wolfssl_wolfcrypt_Des3_NULL
#define com_wolfssl_wolfcrypt_Des3_NULL 0LL
#undef com_wolfssl_wolfcrypt_Des3_KEY_SIZE
#define com_wolfssl_wolfcrypt_Des3_KEY_SIZE 24L
#undef com_wolfssl_wolfcrypt_Des3_BLOCK_SIZE
#define com_wolfssl_wolfcrypt_Des3_BLOCK_SIZE 8L
#undef com_wolfssl_wolfcrypt_Des3_ENCRYPT_MODE
#define com_wolfssl_wolfcrypt_Des3_ENCRYPT_MODE 0L
#undef com_wolfssl_wolfcrypt_Des3_DECRYPT_MODE
#define com_wolfssl_wolfcrypt_Des3_DECRYPT_MODE 1L
/*
 * Class:     com_wolfssl_wolfcrypt_Des3
 * Method:    mallocNativeStruct
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_wolfcrypt_Des3_mallocNativeStruct
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
