/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_wolfcrypt_Sha512 */

#ifndef _Included_com_wolfssl_wolfcrypt_Sha512
#define _Included_com_wolfssl_wolfcrypt_Sha512
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wolfssl_wolfcrypt_Sha512_NULL
#define com_wolfssl_wolfcrypt_Sha512_NULL 0LL
#undef com_wolfssl_wolfcrypt_Sha512_TYPE
#define com_wolfssl_wolfcrypt_Sha512_TYPE 4L
#undef com_wolfssl_wolfcrypt_Sha512_DIGEST_SIZE
#define com_wolfssl_wolfcrypt_Sha512_DIGEST_SIZE 64L
/*
 * Class:     com_wolfssl_wolfcrypt_Sha512
 * Method:    mallocNativeStruct
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_wolfcrypt_Sha512_mallocNativeStruct
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
