/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_wolfcrypt_WolfSSLCertManager */

#ifndef _Included_com_wolfssl_wolfcrypt_WolfSSLCertManager
#define _Included_com_wolfssl_wolfcrypt_WolfSSLCertManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wolfssl_wolfcrypt_WolfSSLCertManager
 * Method:    CertManagerNew
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_wolfcrypt_WolfSSLCertManager_CertManagerNew
  (JNIEnv *, jclass);

/*
 * Class:     com_wolfssl_wolfcrypt_WolfSSLCertManager
 * Method:    CertManagerFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_WolfSSLCertManager_CertManagerFree
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_wolfssl_wolfcrypt_WolfSSLCertManager
 * Method:    CertManagerLoadCA
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_WolfSSLCertManager_CertManagerLoadCA
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     com_wolfssl_wolfcrypt_WolfSSLCertManager
 * Method:    CertManagerLoadCABuffer
 * Signature: (J[BJI)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_WolfSSLCertManager_CertManagerLoadCABuffer
  (JNIEnv *, jclass, jlong, jbyteArray, jlong, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_WolfSSLCertManager
 * Method:    CertManagerUnloadCAs
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_WolfSSLCertManager_CertManagerUnloadCAs
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_wolfssl_wolfcrypt_WolfSSLCertManager
 * Method:    CertManagerVerifyBuffer
 * Signature: (J[BJI)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_WolfSSLCertManager_CertManagerVerifyBuffer
  (JNIEnv *, jclass, jlong, jbyteArray, jlong, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_WolfSSLCertManager
 * Method:    CertManagerEnableCRL
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_WolfSSLCertManager_CertManagerEnableCRL
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_WolfSSLCertManager
 * Method:    CertManagerDisableCRL
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_WolfSSLCertManager_CertManagerDisableCRL
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_wolfssl_wolfcrypt_WolfSSLCertManager
 * Method:    CertManagerLoadCRLBuffer
 * Signature: (J[BJI)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_WolfSSLCertManager_CertManagerLoadCRLBuffer
  (JNIEnv *, jclass, jlong, jbyteArray, jlong, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_WolfSSLCertManager
 * Method:    CertManagerSetVerify
 * Signature: (JLjava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_WolfSSLCertManager_CertManagerSetVerify
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_WolfSSLCertManager
 * Method:    CertManagerClearVerify
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_WolfSSLCertManager_CertManagerClearVerify
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
