/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_wolfcrypt_AesXts */

#ifndef _Included_com_wolfssl_wolfcrypt_AesXts
#define _Included_com_wolfssl_wolfcrypt_AesXts
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wolfssl_wolfcrypt_AesXts_NULL
#define com_wolfssl_wolfcrypt_AesXts_NULL 0LL
#undef com_wolfssl_wolfcrypt_AesXts_KEY_SIZE_128
#define com_wolfssl_wolfcrypt_AesXts_KEY_SIZE_128 32L
#undef com_wolfssl_wolfcrypt_AesXts_KEY_SIZE_192
#define com_wolfssl_wolfcrypt_AesXts_KEY_SIZE_192 48L
#undef com_wolfssl_wolfcrypt_AesXts_KEY_SIZE_256
#define com_wolfssl_wolfcrypt_AesXts_KEY_SIZE_256 64L
#undef com_wolfssl_wolfcrypt_AesXts_BLOCK_SIZE
#define com_wolfssl_wolfcrypt_AesXts_BLOCK_SIZE 16L
#undef com_wolfssl_wolfcrypt_AesXts_TWEAK_SIZE
#define com_wolfssl_wolfcrypt_AesXts_TWEAK_SIZE 16L
#undef com_wolfssl_wolfcrypt_AesXts_MAX_DATA_UNIT_SIZE
#define com_wolfssl_wolfcrypt_AesXts_MAX_DATA_UNIT_SIZE 16777216L
#undef com_wolfssl_wolfcrypt_AesXts_ENCRYPT_MODE
#define com_wolfssl_wolfcrypt_AesXts_ENCRYPT_MODE 0L
#undef com_wolfssl_wolfcrypt_AesXts_DECRYPT_MODE
#define com_wolfssl_wolfcrypt_AesXts_DECRYPT_MODE 1L
/*
 * Class:     com_wolfssl_wolfcrypt_AesXts
 * Method:    mallocNativeStruct_internal
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_wolfcrypt_AesXts_mallocNativeStruct_1internal
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_AesXts
 * Method:    native_free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_AesXts_native_1free
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_AesXts
 * Method:    native_set_key_internal
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_AesXts_native_1set_1key_1internal
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_AesXts
 * Method:    native_update_internal
 * Signature: (I[BII[BI[B)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_AesXts_native_1update_1internal__I_3BII_3BI_3B
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint, jbyteArray, jint, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_AesXts
 * Method:    native_update_internal
 * Signature: (ILjava/nio/ByteBuffer;IILjava/nio/ByteBuffer;I[B)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_AesXts_native_1update_1internal__ILjava_nio_ByteBuffer_2IILjava_nio_ByteBuffer_2I_3B
  (JNIEnv *, jobject, jint, jobject, jint, jint, jobject, jint, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_AesXts
 * Method:    native_update_sector_internal
 * Signature: (I[BII[BIJ)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_AesXts_native_1update_1sector_1internal__I_3BII_3BIJ
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint, jbyteArray, jint, jlong);

/*
 * Class:     com_wolfssl_wolfcrypt_AesXts
 * Method:    native_update_sector_internal
 * Signature: (ILjava/nio/ByteBuffer;IILjava/nio/ByteBuffer;IJ)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_AesXts_native_1update_1sector_1internal__ILjava_nio_ByteBuffer_2IILjava_nio_ByteBuffer_2IJ
  (JNIEnv *, jobject, jint, jobject, jint, jint, jobject, jint, jlong);

/*
 * Class:     com_wolfssl_wolfcrypt_AesXts
 * Method:    native_stream_init_internal
 * Signature: (I[B)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_AesXts_native_1stream_1init_1internal
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_AesXts
 * Method:    native_stream_update_internal
 * Signature: (I[BII[BIZ)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_AesXts_native_1stream_1update_1internal__I_3BII_3BIZ
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint, jbyteArray, jint, jboolean);

/*
 * Class:     com_wolfssl_wolfcrypt_AesXts
 * Method:    native_stream_update_internal
 * Signature: (ILjava/nio/ByteBuffer;IILjava/nio/ByteBuffer;IZ)I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_AesXts_native_1stream_1update_1internal__ILjava_nio_ByteBuffer_2IILjava_nio_ByteBuffer_2IZ
  (JNIEnv *, jobject, jint, jobject, jint, jint, jobject, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
