/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_wolfcrypt_Sha256 */

#ifndef _Included_com_wolfssl_wolfcrypt_Sha256
#define _Included_com_wolfssl_wolfcrypt_Sha256
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wolfssl_wolfcrypt_Sha256_NULL
#define com_wolfssl_wolfcrypt_Sha256_NULL 0LL
#undef com_wolfssl_wolfcrypt_Sha256_TYPE
#define com_wolfssl_wolfcrypt_Sha256_TYPE 2L
#undef com_wolfssl_wolfcrypt_Sha256_DIGEST_SIZE
#define com_wolfssl_wolfcrypt_Sha256_DIGEST_SIZE 32L
/*
 * Class:     com_wolfssl_wolfcrypt_Sha256
 * Method:    mallocNativeStruct
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_wolfcrypt_Sha256_mallocNativeStruct
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Sha256
 * Method:    initSha256
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Sha256_initSha256
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Sha256
 * Method:    sha256Update
 * Signature: (Ljava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Sha256_sha256Update__Ljava_nio_ByteBuffer_2II
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_Sha256
 * Method:    sha256Update
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Sha256_sha256Update___3BII
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_Sha256
 * Method:    sha256Final
 * Signature: (Ljava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Sha256_sha256Final__Ljava_nio_ByteBuffer_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_Sha256
 * Method:    sha256Final
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Sha256_sha256Final___3B
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
