/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_wolfcrypt_Rsa */

#ifndef _Included_com_wolfssl_wolfcrypt_Rsa
#define _Included_com_wolfssl_wolfcrypt_Rsa
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wolfssl_wolfcrypt_Rsa_NULL
#define com_wolfssl_wolfcrypt_Rsa_NULL 0LL
/*
 * Class:     com_wolfssl_wolfcrypt_Rsa
 * Method:    mallocNativeStruct
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_wolfcrypt_Rsa_mallocNativeStruct
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_Rsa
 * Method:    decodeRawPublicKey
 * Signature: (Ljava/nio/ByteBuffer;JLjava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_Rsa_decodeRawPublicKey
  (JNIEnv *, jobject, jobject, jlong, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
