/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfssl_wolfcrypt_MlKem */

#ifndef _Included_com_wolfssl_wolfcrypt_MlKem
#define _Included_com_wolfssl_wolfcrypt_MlKem
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wolfssl_wolfcrypt_MlKem_NULL
#define com_wolfssl_wolfcrypt_MlKem_NULL 0LL
#undef com_wolfssl_wolfcrypt_MlKem_ML_KEM_512
#define com_wolfssl_wolfcrypt_MlKem_ML_KEM_512 512L
#undef com_wolfssl_wolfcrypt_MlKem_ML_KEM_768
#define com_wolfssl_wolfcrypt_MlKem_ML_KEM_768 768L
#undef com_wolfssl_wolfcrypt_MlKem_ML_KEM_1024
#define com_wolfssl_wolfcrypt_MlKem_ML_KEM_1024 1024L
#undef com_wolfssl_wolfcrypt_MlKem_ML_KEM_SEED_SIZE
#define com_wolfssl_wolfcrypt_MlKem_ML_KEM_SEED_SIZE 64L
#undef com_wolfssl_wolfcrypt_MlKem_ML_KEM_SHARED_SECRET_SIZE
#define com_wolfssl_wolfcrypt_MlKem_ML_KEM_SHARED_SECRET_SIZE 32L
#undef com_wolfssl_wolfcrypt_MlKem_ML_KEM_ENCAPS_RANDOM_SIZE
#define com_wolfssl_wolfcrypt_MlKem_ML_KEM_ENCAPS_RANDOM_SIZE 32L
#undef com_wolfssl_wolfcrypt_MlKem_ML_KEM_512_PUBLIC_KEY_SIZE
#define com_wolfssl_wolfcrypt_MlKem_ML_KEM_512_PUBLIC_KEY_SIZE 800L
#undef com_wolfssl_wolfcrypt_MlKem_ML_KEM_512_PRIVATE_KEY_SIZE
#define com_wolfssl_wolfcrypt_MlKem_ML_KEM_512_PRIVATE_KEY_SIZE 1632L
#undef com_wolfssl_wolfcrypt_MlKem_ML_KEM_512_CIPHERTEXT_SIZE
#define com_wolfssl_wolfcrypt_MlKem_ML_KEM_512_CIPHERTEXT_SIZE 768L
#undef com_wolfssl_wolfcrypt_MlKem_ML_KEM_768_PUBLIC_KEY_SIZE
#define com_wolfssl_wolfcrypt_MlKem_ML_KEM_768_PUBLIC_KEY_SIZE 1184L
#undef com_wolfssl_wolfcrypt_MlKem_ML_KEM_768_PRIVATE_KEY_SIZE
#define com_wolfssl_wolfcrypt_MlKem_ML_KEM_768_PRIVATE_KEY_SIZE 2400L
#undef com_wolfssl_wolfcrypt_MlKem_ML_KEM_768_CIPHERTEXT_SIZE
#define com_wolfssl_wolfcrypt_MlKem_ML_KEM_768_CIPHERTEXT_SIZE 1088L
#undef com_wolfssl_wolfcrypt_MlKem_ML_KEM_1024_PUBLIC_KEY_SIZE
#define com_wolfssl_wolfcrypt_MlKem_ML_KEM_1024_PUBLIC_KEY_SIZE 1568L
#undef com_wolfssl_wolfcrypt_MlKem_ML_KEM_1024_PRIVATE_KEY_SIZE
#define com_wolfssl_wolfcrypt_MlKem_ML_KEM_1024_PRIVATE_KEY_SIZE 3168L
#undef com_wolfssl_wolfcrypt_MlKem_ML_KEM_1024_CIPHERTEXT_SIZE
#define com_wolfssl_wolfcrypt_MlKem_ML_KEM_1024_CIPHERTEXT_SIZE 1568L
/*
 * Class:     com_wolfssl_wolfcrypt_MlKem
 * Method:    mallocNativeStruct
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wolfssl_wolfcrypt_MlKem_mallocNativeStruct
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_MlKem
 * Method:    wc_mlkem_init
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_MlKem_wc_1mlkem_1init
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wolfssl_wolfcrypt_MlKem
 * Method:    wc_mlkem_free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_MlKem_wc_1mlkem_1free
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_MlKem
 * Method:    wc_mlkem_make_key
 * Signature: (Lcom/wolfssl/wolfcrypt/Rng;)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_MlKem_wc_1mlkem_1make_1key
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_MlKem
 * Method:    wc_mlkem_make_key_from_seed
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_MlKem_wc_1mlkem_1make_1key_1from_1seed
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_MlKem
 * Method:    wc_mlkem_encapsulate
 * Signature: (Lcom/wolfssl/wolfcrypt/Rng;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_wolfcrypt_MlKem_wc_1mlkem_1encapsulate
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_MlKem
 * Method:    wc_mlkem_encapsulate_with_random
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_wolfcrypt_MlKem_wc_1mlkem_1encapsulate_1with_1random
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_MlKem
 * Method:    wc_mlkem_decapsulate
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_wolfcrypt_MlKem_wc_1mlkem_1decapsulate
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_MlKem
 * Method:    wc_mlkem_export_public
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_wolfcrypt_MlKem_wc_1mlkem_1export_1public
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_MlKem
 * Method:    wc_mlkem_export_private
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wolfssl_wolfcrypt_MlKem_wc_1mlkem_1export_1private
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_MlKem
 * Method:    wc_mlkem_import_public
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_MlKem_wc_1mlkem_1import_1public
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_MlKem
 * Method:    wc_mlkem_import_private
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_wolfssl_wolfcrypt_MlKem_wc_1mlkem_1import_1private
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_wolfssl_wolfcrypt_MlKem
 * Method:    wc_mlkem_public_key_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_MlKem_wc_1mlkem_1public_1key_1size
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_MlKem
 * Method:    wc_mlkem_private_key_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_MlKem_wc_1mlkem_1private_1key_1size
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_MlKem
 * Method:    wc_mlkem_ciphertext_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_MlKem_wc_1mlkem_1ciphertext_1size
  (JNIEnv *, jobject);

/*
 * Class:     com_wolfssl_wolfcrypt_MlKem
 * Method:    wc_mlkem_shared_secret_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wolfssl_wolfcrypt_MlKem_wc_1mlkem_1shared_1secret_1size
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
